spring:
  cloud:
    stream:
      bindings:
        weatherEventConsumer-in-0:
          destination: sync-weather
          group: weather-archive
#          binder: ${spring.profiles.active:kafka}
        weatherEventConsumer-out-0:
          destination: sync-weather
#          binder: ${spring.profiles.active:kafka}
      default-binder: ${spring.profiles.active:kafka}
      # if there are more than 1 binder either default one should be specified or channel should have binder
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                streams:
                  bootstrap-servers: "localhost: 9092"
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672


